[tool.poetry]
name = "poetry gh"
version = "0.1.0"
description = "tutorial github usando poetry"
authors = ["Polyana"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
